### ISSUE TITLE
s6-linux-init-maker checks for utmp user in passwd

### ISSUE THREAD

**Issue by firasuke** [skarnet/s6-linux-init#1]
s6-linux-init-maker checks for utmp user in passwd even when the default `root` user is chosen.

To reproduce:

1. Ensure that no `utmp` user is in `/etc/passwd`.

2. Run the following (with or without `-u root`):
```M
s6-linux-init-maker -c /etc/s6 -G agetty -p /usr/bin some_directory
```

Error:
```M
s6-linux-init-maker: fatal: unable to find user utmp in passwd database
```

**Comment by skarnet** [comment]
Even with `-U root` ? (note: capital U)

**Comment by firasuke** [comment]
I didn't try it, but I do have `utmps` enabled and it could be due to that.

**Comment by skarnet** [comment]
Yes, when you build s6-linux-init with utmps support, it assumes you want the utmps services and creates them with the `utmp` user by default. You can change that with `-U foobar` so the utmps services run as `foobar`, or with `-U ""` if you don't want the utmps services at all.

**Comment by skarnet** [comment]
@firasuke Do you still have an issue with `s6-linux-init-maker` or can I close this?

**Comment by firasuke** [comment]
I haven't attempted your suggestion, but you can close it for now.

I'll reopen it if the issue still persists.

Thanks for your time and effort.

**Comment by firasuke** [comment]
Using `-U root` works, and the error is no longer showing!

Thanks again!

**Comment by skarnet** [comment]
np ;-)

**Comment by skarnet** [comment]
np, but note that the utmpd and wtmpd services will still be enabled with `-U root`. If you want to entirely disable them, use `-U ""`.

**Comment by firasuke** [comment]
If I wanted to use `utmps` with the user `root` instead of the user `utmp`, why would I want to disable the `utmpd` and `wtmpd` services? Or you're only mentioning this as being optional?

**Comment by skarnet** [comment]
Only optional. If using the utmpd/wtmpd services as root is what you want, then by all means, use `-U root`. :-)

**Comment by firasuke** [comment]
Fair enough, thanks again.
