### ISSUE TITLE
The `run` file for `utmpd` isn't terminated by a newline character

### ISSUE THREAD

**Issue by firasuke** [skarnet/s6-linux-init#4]
When running `s6-linux-init-maker` with `-U`, the generated `utmpd/run` file isn't null terminated (as opposed to previous versions of s6-l-i-m).

Is that intended?

**Comment by skarnet** [comment]
Nope, just a slight (and harmless) oversight. Thanks for the report, fixed in the latest commit. 😉

**Comment by firasuke** [comment]
Glad I could help.
